# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_analyticssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssettings',
            name='google_analytics',
            field=models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=15, null=True),
        ),
    ]
